### ISSUE TITLE
dataset of call recording and ravdess is different

### ISSUE THREAD

**Issue by dimanshu** [shaharpit809/Audio-Sentiment-Analysis#1]
dataset of call recording and ravdess is different it will create the problem ? 
and yes will it solve the problem to not catch high pitch sound as anger.
like generally i speak very loudly so it will detect my voice as anger ?

**Comment by shaharpit809** [comment]
Hi @dimanshu ,

Thank you for your message. Having different datasets from different dialects does create problems. It is preferable to use data that is similar to the training data to capture the emotion in the most efficient manner. 
Again, the model will output how you train it. If the training data has loud emotion for `angry` audio clips then it will consider loud sound as anger. You can try using more audio features and check if its working or not.
